---
- name: configuration maven and build
  hosts: maven
  become: yes

  tasks:
    - name: Install the latest version
      apt:
        name:
          - git
          - maven
        state: present

    - name: clone project git
      git:
        repo: https://github.com/daticahealth/java-tomcat-maven-example
        dest: /opt/app/

    - name: run mvn
      shell: "mvn package"
      args:
        chdir: "/opt/app"

    - name: fetch file war
      fetch:
        src: /opt/app/target/java-tomcat-maven-example.war
        dst: /tmp/
        flat: yes


- name: configuration tomcat
  hosts: tomcat
  become: yes

  tasks:
    - name: Install the latest version
      apt:
        name:
        - default-jdk
        - tomcat9
        state: present

    - name: copy file war
      copy:
        src: /tmp/java-tomcat-maven-example.war
        dst: /var/lib/tomcat9/webapps/

    - name: restart tomcat
      service:
        name: tomcat9
        state: restarted