services:
  maven:
    build:
      context: .
      dockerfile_inline: |
        FROM maven:latest
        WORKDIR /app
        RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git && \
        cd boxfuse-sample-java-war-hello && mvn package
    volumes:
      - type: volume
        source: app
        target: /app/boxfuse-sample-java-war-hello/target
  tomcat:
    image: tomcat:jre8-alpine
    ports:
      - "8080:8080"
    depends_on:
      - maven
    restart: unless-stopped
volumes:
  app: