services:
  maven:
    build:
      context: .
      dockerfile_inline: |
        FROM maven:latest
        WORKDIR /app
        RUN git clone https://github.com/daticahealth/java-tomcat-maven-example
        WORKDIR /app/java-tomcat-maven-example
        RUN mvn clean package
    volumes:
      - type: volume
        source: app
        target: /app/java-tomcat-maven-example/target
  tomcat:
    image: tomcat:jre8-alpine
    ports:
      - "8080:8080"
    depends_on:
      - maven
    restart: unless-stopped
    volumes:
      - type: volume
        source: app
        target: /usr/local/tomcat/webapps
volumes:
    app: